#!/bin/sh
set -x

br_name=br0

if ! [ -n "$1" ];then
    echo "Error: no interface specified"
    exit 1
fi

ip link set $1 down
ip link delete $1

if ! (ip link show | grep tap > /dev/null); then 
    ip link set $br_name down
    ip link delete $br_name
    sleep 0.5s
    sudo systemctl restart NetworkManager.service
fi

exit 0

